# Generated by Django 4.0.2 on 2022-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='district',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
