# Generated by Django 4.0.2 on 2022-04-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_alter_activities_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='activities',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
