# Generated by Django 4.0.2 on 2022-04-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_alter_activities_name_alter_activities_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='name',
            new_name='title',
        ),
    ]
