# Generated by Django 4.0.2 on 2022-04-13 15:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_rename_name_activities_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
