# Generated by Django 4.0.2 on 2022-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_activities_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='old_price',
            field=models.CharField(default='xxxxx', max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='altitude',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='difficulty',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='distance',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='duration_days',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='thumbnail',
            field=models.ImageField(default='images/whiteBG.jpg', upload_to='upload/activities'),
        ),
    ]
