# Generated by Django 4.0.2 on 2022-04-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0006_activities_old_price_alter_activities_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='banner_quote',
            field=models.CharField(default='', max_length=160),
        ),
    ]
