# Generated by Django 4.0.2 on 2022-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0009_alter_activities_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='altitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='banner_quote',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='distance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='duration_days',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='old_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
