# Generated by Django 4.0.2 on 2022-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0010_alter_activities_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='thumbnail_2',
            field=models.ImageField(default='images/whiteBG.jpg', upload_to='upload/activities'),
        ),
        migrations.AddField(
            model_name='activities',
            name='thumbnail_3',
            field=models.ImageField(default='images/whiteBG.jpg', upload_to='upload/activities'),
        ),
        migrations.AddField(
            model_name='activities',
            name='thumbnail_4',
            field=models.ImageField(default='images/whiteBG.jpg', upload_to='upload/activities'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='thumbnail',
            field=models.ImageField(default='images/whiteBG.jpg', upload_to='uplo ad/activities'),
        ),
    ]
