# Generated by Django 4.0.2 on 2022-03-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_transaction_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Refunds', 'Refunds'), ('Renting', 'Renting'), ('IT and Maintenance', 'IT and Maintenance'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=20),
        ),
    ]
