# Generated by Django 4.0.2 on 2022-03-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('IT and Maintenance', 'IT and Maintenance'), ('Renting', 'Renting'), ('Marketing', 'Marketing'), ('Refunds', 'Refunds'), ('Sales', 'Sales'), ('Miscellaneous', 'Miscellaneous'), ('Purchase', 'Purchase')], default='Miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=6),
        ),
    ]
