# Generated by Django 4.0.2 on 2022-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('IT and Maintenance', 'IT and Maintenance'), ('Refunds', 'Refunds'), ('Sales', 'Sales'), ('Miscellaneous', 'Miscellaneous'), ('Renting', 'Renting'), ('Purchase', 'Purchase'), ('Marketing', 'Marketing')], default='Miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=6),
        ),
    ]
