# Generated by Django 4.0.2 on 2022-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Miscellaneous', 'Miscellaneous'), ('Purchase', 'Purchase'), ('Refunds', 'Refunds'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('IT and Maintenance', 'IT and Maintenance'), ('Renting', 'Renting')], default='Miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6),
        ),
    ]
