# Generated by Django 4.0.2 on 2022-04-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Miscellaneous', 'Miscellaneous'), ('Refunds', 'Refunds'), ('Renting', 'Renting'), ('IT and Maintenance', 'IT and Maintenance'), ('Purchase', 'Purchase'), ('Sales', 'Sales')], default='Miscellaneous', max_length=20),
        ),
    ]
