# Generated by Django 4.0.2 on 2022-04-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Miscellaneous', 'Miscellaneous'), ('Marketing', 'Marketing'), ('IT and Maintenance', 'IT and Maintenance'), ('Sales', 'Sales'), ('Renting', 'Renting'), ('Refunds', 'Refunds')], default='Miscellaneous', max_length=20),
        ),
    ]
