# Generated by Django 4.0.2 on 2022-04-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Renting', 'Renting'), ('Miscellaneous', 'Miscellaneous'), ('Refunds', 'Refunds'), ('Marketing', 'Marketing'), ('IT and Maintenance', 'IT and Maintenance'), ('Purchase', 'Purchase'), ('Sales', 'Sales')], default='Miscellaneous', max_length=20),
        ),
    ]
