# Generated by Django 4.0.2 on 2022-04-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('IT and Maintenance', 'IT and Maintenance'), ('Sales', 'Sales'), ('Renting', 'Renting'), ('Refunds', 'Refunds'), ('Miscellaneous', 'Miscellaneous'), ('Marketing', 'Marketing')], default='Miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=6),
        ),
    ]
