# Generated by Django 4.0.2 on 2022-04-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Renting', 'Renting'), ('Miscellaneous', 'Miscellaneous'), ('Refunds', 'Refunds'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Marketing', 'Marketing'), ('IT and Maintenance', 'IT and Maintenance')], default='Miscellaneous', max_length=20),
        ),
    ]
