# Generated by Django 4.0.2 on 2022-04-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Refunds', 'Refunds'), ('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Renting', 'Renting'), ('Miscellaneous', 'Miscellaneous'), ('IT and Maintenance', 'IT and Maintenance'), ('Marketing', 'Marketing')], default='Miscellaneous', max_length=20),
        ),
    ]
