# Generated by Django 4.0.2 on 2022-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Renting', 'Renting'), ('Miscellaneous', 'Miscellaneous'), ('Purchase', 'Purchase'), ('IT and Maintenance', 'IT and Maintenance'), ('Refunds', 'Refunds'), ('Marketing', 'Marketing')], default='Miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6),
        ),
    ]
