# Generated by Django 4.0.2 on 2022-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Renting', 'Renting'), ('Refunds', 'Refunds'), ('Sales', 'Sales'), ('Miscellaneous', 'Miscellaneous'), ('IT and Maintenance', 'IT and Maintenance'), ('Purchase', 'Purchase')], default='Miscellaneous', max_length=20),
        ),
    ]
