# Generated by Django 4.0.2 on 2022-04-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0026_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Renting', 'Renting'), ('IT and Maintenance', 'IT and Maintenance'), ('Refunds', 'Refunds'), ('Purchase', 'Purchase'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=20),
        ),
    ]
