# Generated by Django 4.0.2 on 2022-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0027_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Miscellaneous', 'Miscellaneous'), ('Purchase', 'Purchase'), ('Renting', 'Renting'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Refunds', 'Refunds'), ('IT and Maintenance', 'IT and Maintenance')], default='Miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=6),
        ),
    ]
