# Generated by Django 4.0.2 on 2022-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0028_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Refunds', 'Refunds'), ('Renting', 'Renting'), ('Sales', 'Sales'), ('Miscellaneous', 'Miscellaneous'), ('Marketing', 'Marketing'), ('IT and Maintenance', 'IT and Maintenance'), ('Purchase', 'Purchase')], default='Miscellaneous', max_length=20),
        ),
    ]
