# Generated by Django 4.0.2 on 2022-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Miscellaneous', 'Miscellaneous'), ('Purchase', 'Purchase'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('IT and Maintenance', 'IT and Maintenance'), ('Refunds', 'Refunds'), ('Renting', 'Renting')], default='Miscellaneous', max_length=20),
        ),
    ]
