# Generated by Django 4.0.2 on 2022-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0033_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Miscellaneous', 'Miscellaneous'), ('Sales', 'Sales'), ('Renting', 'Renting'), ('Refunds', 'Refunds'), ('Purchase', 'Purchase'), ('Marketing', 'Marketing'), ('IT and Maintenance', 'IT and Maintenance')], default='Miscellaneous', max_length=20),
        ),
    ]
