# Generated by Django 4.0.2 on 2022-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0036_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Miscellaneous', 'Miscellaneous'), ('Marketing', 'Marketing'), ('Renting', 'Renting'), ('Refunds', 'Refunds'), ('Sales', 'Sales'), ('IT and Maintenance', 'IT and Maintenance')], default='Miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6),
        ),
    ]
