# Generated by Django 4.0.2 on 2022-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0037_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Refunds', 'Refunds'), ('IT and Maintenance', 'IT and Maintenance'), ('Purchase', 'Purchase'), ('Renting', 'Renting'), ('Marketing', 'Marketing'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=6),
        ),
    ]
