# Generated by Django 4.0.2 on 2022-04-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0038_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Miscellaneous', 'Miscellaneous'), ('Renting', 'Renting'), ('IT and Maintenance', 'IT and Maintenance'), ('Marketing', 'Marketing'), ('Purchase', 'Purchase'), ('Refunds', 'Refunds')], default='Miscellaneous', max_length=20),
        ),
    ]
