# Generated by Django 4.0.2 on 2022-04-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0039_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Renting', 'Renting'), ('Marketing', 'Marketing'), ('Miscellaneous', 'Miscellaneous'), ('Refunds', 'Refunds'), ('Sales', 'Sales'), ('IT and Maintenance', 'IT and Maintenance'), ('Purchase', 'Purchase')], default='Miscellaneous', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6),
        ),
    ]
