# Generated by Django 4.0.2 on 2022-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0043_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('IT and Maintenance', 'IT and Maintenance'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Renting', 'Renting'), ('Marketing', 'Marketing'), ('Miscellaneous', 'Miscellaneous'), ('Refunds', 'Refunds')], default='Miscellaneous', max_length=20),
        ),
    ]
