# Generated by Django 4.0.2 on 2022-02-11 16:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
