# Generated by Django 4.0.2 on 2022-02-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_customer__history_change_reason_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='_history_change_reason_field',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='_history_change_reason_field',
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
