# Generated by Django 4.0.2 on 2022-02-12 05:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_remove_customer__history_change_reason_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='customer_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
