# Generated by Django 4.0.2 on 2022-04-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Activities', '0005_activities_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_location', models.CharField(max_length=40)),
                ('office_phone', models.CharField(max_length=30)),
                ('office_email', models.EmailField(max_length=254)),
                ('office_timings', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=160)),
                ('about_us', models.CharField(max_length=160)),
                ('testimonials', models.CharField(max_length=250)),
                ('bottom_banner', models.CharField(max_length=160)),
                ('footer', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=40)),
                ('description1', models.TextField(max_length=100)),
                ('title2', models.CharField(max_length=40)),
                ('description2', models.TextField(max_length=100)),
                ('title3', models.CharField(max_length=40)),
                ('description3', models.TextField(max_length=100)),
                ('title4', models.CharField(max_length=40)),
                ('description4', models.TextField(max_length=100)),
                ('title5', models.CharField(max_length=40)),
                ('description5', models.TextField(max_length=100)),
                ('title6', models.CharField(max_length=40)),
                ('description6', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(upload_to='upload/profilePicture/%Y/%m/%d')),
                ('coming_from', models.CharField(max_length=40)),
                ('review', models.TextField(max_length=150)),
                ('recommended', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_Image', models.ImageField(upload_to='uploads/images/%Y/%m/%d')),
                ('video1', models.FileField(upload_to='upload/videos/%Y/%m/%d')),
                ('video2', models.FileField(upload_to='upload/videos/%Y/%m/%d')),
                ('video3', models.FileField(upload_to='upload/videos/%Y/%m/%d')),
                ('video4', models.FileField(upload_to='upload/videos/%Y/%m/%d')),
                ('footer_Image', models.ImageField(upload_to='uploads/images/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Home Videos',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/gallery/%Y/%m/%d')),
                ('recommended', models.BooleanField(blank=True, default=False, null=True)),
                ('location', models.CharField(max_length=40)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activities.activitiescategories')),
            ],
        ),
    ]
