# Generated by Django 4.0.2 on 2022-04-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_Image', models.ImageField(upload_to='uploads/images/%Y/%m/%d')),
                ('video1', models.FileField(upload_to='uploads/videos/%Y/%m/%d')),
                ('video2', models.FileField(upload_to='uploads/videos/%Y/%m/%d')),
                ('video3', models.FileField(upload_to='uploads/videos/%Y/%m/%d')),
                ('video4', models.FileField(upload_to='uploads/videos/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Home Videos',
            },
        ),
    ]
