# Generated by Django 4.0.2 on 2022-04-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=40)),
                ('description1', models.TextField(max_length=100)),
                ('title2', models.CharField(max_length=40)),
                ('description2', models.TextField(max_length=100)),
                ('title3', models.CharField(max_length=40)),
                ('description3', models.TextField(max_length=100)),
                ('title4', models.CharField(max_length=40)),
                ('description4', models.TextField(max_length=100)),
                ('title5', models.CharField(max_length=40)),
                ('description5', models.TextField(max_length=100)),
                ('title6', models.CharField(max_length=40)),
                ('description6', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
