# Generated by Django 4.0.2 on 2022-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('author', models.CharField(max_length=40)),
                ('thumbnail', models.URLField(max_length=250)),
            ],
        ),
    ]
