# Generated by Django 4.0.2 on 2022-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_url',
            field=models.URLField(default='https://www.hashstrix.com/tag/traveloft/', max_length=250),
        ),
        migrations.AddField(
            model_name='blogs',
            name='recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
