# Generated by Django 4.0.2 on 2022-04-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_activities_content'),
        ('Index', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video1',
            field=models.FileField(upload_to='upload/videos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video2',
            field=models.FileField(upload_to='upload/videos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video3',
            field=models.FileField(upload_to='upload/videos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video4',
            field=models.FileField(upload_to='upload/videos/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='upload/gallery/%Y/%m/%d')),
                ('recommended', models.BooleanField(blank=True, default=False, null=True)),
                ('location', models.CharField(max_length=40)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Activities.activitiescategories')),
            ],
        ),
    ]
