# Generated by Django 4.0.2 on 2022-04-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_blogs_blog_url_blogs_recommended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name_plural': 'ContactDetails'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials'},
        ),
    ]
