# Generated by Django 4.0.2 on 2022-06-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0006_aboutus_newsletter_privacypolicy_termscondition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
